swagger: '2.0'
info:
  description: |
    SBA API is structured around REST. Having predictable resource-oriented URLs, our APIs accept form-encoded request bodies, return JSON responses, and use standard HTTP response codes, authentication, and verbs.
    
    ### Supported document formats
    YAP currently supports PNG, JPEG, and PDF, TIFF, XLSX  formats.

    ### File size
    Image files sent to the YAP API should not exceed 100 MB (4 MB for the free tier). Reducing your file size can significantly improve throughput; however, be careful not to reduce image quality in the process.
    
    ### Image and PDF requirements
    - For PDF and TIFF files, up to 2000 pages (only first two pages for the free tier) are processed.
    - Dimensions at least 50 x 50 pixels and at most 10000 x 10000 pixels.
    - The PDF dimensions must be at most 17 x 17 inches, corresponding to legal or A3 paper sizes and smaller.

  version: 3.0.0
  title: SBA Compta - API Inference
  termsOfService: https://dataleon.ai/terms-of-use
  contact:
    email: support@dataleon.ai


tags:
- name: Document Understanding v3
  description: Document understanding IA v3
    
# schemes:
# - http
paths:
  /sba/v3/pre-processing:
    post:
      tags:
      - Document Understanding v3
      summary: Understand deep image and pdf with 5 tasks
      consumes:
      - application/json
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - name: file
        in: formData
        description: file to upload
        required: true
        type: file
      - name: callback_url
        in: formData
        description: Offline processing
        required: false
        type: string
      - name: workspace_id
        in: formData
        description: Add your workspace_id
        required: true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Entity'
        401:
          description: No valid API key provided.
        403:
          description: The API key doesn't have permissions to perform the request.
        422:
          description: The server understands the content type of the request entity (hence a 415 Unsupported Media Type status code is inappropriate),
        429:
          description: Too many requests hit the API too quickly. We recommend an exponential backoff of your requests.
      security:
      - api_key: []

  /sba/v3/pre-processing/dev:
    post:
      tags:
      - Document Understanding v3
      summary: Understand deep image and pdf with 5 tasks
      consumes:
      - application/json
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - name: file
        in: formData
        description: file to upload
        required: true
        type: file
      - name: callback_url
        in: formData
        description: Offline processing
        required: false
        type: string
      - name: workspace_id
        in: formData
        description: Add your workspace_id
        required: true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Entity'
        401:
          description: No valid API key provided.
        403:
          description: The API key doesn't have permissions to perform the request.
        422:
          description: The server understands the content type of the request entity (hence a 415 Unsupported Media Type status code is inappropriate),
        429:
          description: Too many requests hit the API too quickly. We recommend an exponential backoff of your requests.
      security:
      - api_key: []
    

  /task/{Id}:
    get:
      tags:
      - Operating
      summary: Large file offline processing
      description: Asynchronous ("offline") requests target longer documents. These types of requests start a long-running operations. When this operation finishes it stores output as a JSON file in a specified Young App Platform.
      
      
        When the status field has the succeeded value, the JSON response contains the extracted text content from your image or document. 
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Id
        in: path
        description: ID of task
        required: true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
        401:
          description: No valid API key provided.
        403:
          description: The API key doesn't have permissions to perform the request.
        404:
          description: The requested workfow doesn't exist.
        422:
          description: The server understands the content type of the request entity (hence a 415 Unsupported Media Type status code is inappropriate),
        429:
          description: Too many requests hit the API too quickly. We recommend an exponential backoff of your requests.
      security:
      - api_key: []

securityDefinitions:
  api_key:
    type: apiKey
    name: Api-Key
    in: header

definitions:

  Entity:
    type: object
    properties:
      metadata: 
        type: object
        properties: 
          document_name: 
            type: string
            format: nullable
          status: 
            type: string
            example: successful
            
  ApiResponse:
    type: object
    properties:
      status:
        example: "notStarted|running|failed|succeeded"
        type: string

# Added by API Auto Mocking Plugin
# host: cognitive.youngapp.co
schemes:
 - https
# Added by API Auto Mocking Plugin
# basePath: /v2
# Added by API Auto Mocking Plugin
# host: inference.eu-west-1.dataleon.ai
# basePath: /sba
# Added by API Auto Mocking Plugin
host: inference.eu-west-1.dataleon.ai
basePath: /sba
